### ISSUE TITLE
git clone failed.

### ISSUE THREAD

**Issue by openersoft** [klebs6/surge-rs#2]
HI, me again...
Maybe it's a stupid question. 

OS: Windows

command: _**git clone https://github.com/klebs6/surge-rs.git**_

output:

Cloning into 'surge-rs'...
remote: Enumerating objects: 15334, done.
remote: Counting objects: 100% (3553/3553), done.
remote: Compressing objects: 100% (2074/2074), done.
remote: Total 15334 (delta 1732), reused 2951 (delta 1458), pack-reused 11781Receiving objects: 100% (15334/15334), 26.34 MiB | 582.00 KiB/s
Receiving objects: 100% (15334/15334), 26.39 MiB | 583.00 KiB/s, done.
Resolving deltas: 100% (9015/9015), done.
error: invalid path 'surgefx-flanger/src/aux.rs'
**fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'**
-------------------------------------------------------------------------------------------------
Any suggestions? Thanks!

**Comment by openersoft** [comment]
git config --system core.longpaths true, this is not work

**Comment by klebs6** [comment]
Interesting, thanks for letting me know.  

I'm not quite sure why this happens yet as I don't have access to a windows machine.

I have checked that the `git clone` command does work in a unix environment.
I have also checked that the `surgefx-flanger/src/aux.rs` file mentioned in the error does show up in the `git clone` on unix.

From what I read online, it looks like dashes in filenames on windows should be OK, though full disclosure I am not 100% sure of the quirks of windows development.

I did speak with gpt4 about the issue.  here is what it said:

```
It seems like the issue is related to an invalid path in the repository, which might be due to the use of characters not supported by the Windows filesystem.

Try the following steps:

1. Enable long file paths in Windows:

- Open the Windows Registry Editor (type `regedit` in the search bar and press Enter).
- Navigate to: `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem`
- Look for the value named `LongPathsEnabled`. If it doesn't exist, create a new DWORD value and name it `LongPathsEnabled`.
- Set the value data to `1`.
- Close the Registry Editor and restart your computer.

2. Configure Git to allow long paths:

```bash
git config --global core.longpaths true
```

3. Clone the repository again:

```bash
git clone https://github.com/klebs6/surge-rs.git
```

If the problem persists, you can try cloning the repository into the Windows Subsystem for Linux (WSL), which supports a wider range of characters in file paths. To do this, you'll need to install WSL, enable a Linux distribution, and then clone the repository from within WSL.

Here's how to install WSL:

1. Open PowerShell as an administrator and run:

```powershell
wsl --install
```

2. Restart your computer when prompted.

3. After the restart, open the Microsoft Store and search for a Linux distribution, such as Ubuntu. Install it and then launch it to complete the setup.

4. Once the Linux distribution is set up, open a WSL terminal and run:

```bash
git clone https://github.com/klebs6/surge-rs.git
```

This should allow you to clone the repository without encountering the invalid path issue.
```

what do you think? does this sound like it might help you?

**Comment by openersoft** [comment]
Thanks for you response, I'll try it ! Oh btw,[https://github.com/klebs6/surge-rs/issues/1](url) this is ok now!, but "cargo build" still has some error, like "*** macros  are not working in rust stable channel“，sorry I don't have my mac now, i will paste the context later. good job and thanks for this repo

**Comment by openersoft** [comment]
Maybe it's a Windows system issue, My colleague clone the code take the same error as well. never mind, i just read code first. Thanks for the response!

**Comment by klebs6** [comment]
thanks for letting me know!

there are a few parts of this codebase which were developed on the `nightly` rust channel and probably won't work out of the box on `stable`.

specifically, we have
```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> packed_simd_2-0.3.8/src/lib.rs:214:1
    |
214 | / #![feature(
215 | |     adt_const_params,
216 | |     repr_simd,
217 | |     rustc_attrs,
...   |
224 | |     custom_inner_attributes,
225 | | )]
    | |__^

error[E0554]: `#![feature]` may not be used on the stable release channel
   --> packed_simd_2-0.3.8/src/lib.rs:219:5
    |
219 |     stdsimd,
    |     ^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
   --> packed_simd_2-0.3.8/src/lib.rs:222:5
    |
222 |     core_intrinsics,
    |     ^^^^^^^^^^^^^^^
```
here is some more info about them from the chatbot: 

```
5> what are adt_const_params, repr_simd, rustc_attrs, custom_inner_attributes, stdsimd, core_intrinsics?

`adt_const_params`, `repr_simd`, `rustc_attrs`, `custom_inner_attributes`, `stdsimd`, and `core_intrinsics` are all unstable Rust features that are not yet available on the stable release channel. These features are still in development and are subject to change or removal in future versions of Rust.

Here's a brief explanation of what each feature does:

- `adt_const_params`: Allows constants to be used as generic parameters for types, including struct and enum types.
- `repr_simd`: Allows struct types to be defined with a SIMD representation, which can improve performance when working with large amounts of data.
- `rustc_attrs`: Provides a way to add custom attributes to Rust code that are recognized by the Rust compiler. This can be used to add metadata or perform other custom behavior.
- `custom_inner_attributes`: Provides a way to define custom attributes that can be used inside of Rust item declarations, such as functions or structs.
- `stdsimd`: Provides a standard interface for accessing SIMD instructions across multiple architectures and platforms.
- `core_intrinsics`: Provides access to a set of special Rust functions that map directly to LLVM intrinsics. These functions can be used to perform low-level operations that are not available through the standard Rust library.

Because these features are unstable, they are only available on the nightly build of Rust, which is a version of Rust that is built from the latest source code and may contain experimental or unstable features. To use these features, you will need to install the nightly build of Rust and use the appropriate `#![feature]` declarations in your code.

```

these features are used in various places in this codebase.  specifically useful are the simd features, as well as adt_const_params.


For your use case, it is preferable for you to remain on `stable` channel?

**Comment by openersoft** [comment]
Yes, I'm still on stable channle. I'll switch to nightly when run test code. :)
